package com.grocery.app.constant

object Store {
    const val CATEGORIES = "categories"
    const val PRODUCTS = "products"
    const val RANK = "rank"
    const val NAME = "name"
    const val DESCRIPTION = "description"
    const val PRICE = "price"
    const val ACTIVE = "active"
    const val CATEGORY_ID = "category_id"
    const val ID = "id"
    const val URL = "url"
    const val USERS = "users"
    const val ADDRESS = "address"
    const val TAGS = "tags"
    const val DISCOUNTS = "discounts"
    const val DEALS = "deals"
    const val ADMIN_ROLE = "admin"
    const val SEARCH_KEYS = "search_keys"
    const val CART = "cart"
    const val CREATED_AT = "createdAt"
    const val UPDATED_AT = "updatedAt"
    const val CREATED_BY = "createdBy"
    const val DISCOUNT = "discount"
}